### ISSUE TITLE
Win command

### ISSUE THREAD

**Issue by Bothar** [UB-GEI-SD/B#10]
A la wiki, especifica el següent sobre el win command:

WIN<SP><char>:
  Server sends the winner and his card.

És una mica confús, està malament la descripció i només s'envia la carta del servidor i el client ja comprova qui guanya o està malament la comanda i hauria de ser tipus:
WIN<SP><char><SP><char>

**Comment by jmcano94** [comment]
Això es va dir a classe quan la Núria va escriure el protocol sencer a la pissarra. Client no comprova res, es fia del que digui el servidor. Servidor despres d'haver rebut un SHW per part del client amb la carta d'aquest envia un WIN amb el guanyador. WIN<sp>char<C> o WIN<sp>char<S>. Si que es veritat que s'ha de canviar en el protocol.

**Comment by MrViciao** [comment]
Segun el pdf que hay colgado, se mandan 2 shows. El orden viene determinado por la persona contraria que haya hecho el FOLD/CALL/CHECK. Luego vendria el WIN

**Comment by llevaNEUS** [comment]
Era tarea de todos plasmar en papel el protocolo y mirar los posibles
errores. Yo voy a hacer la pruebas con la versión que expliqué en clase y
cualquier error supondrá suspender la parte de código.

Si hoy os surgen las dudas sobre el protocolo que habéis hecho hasta el
momento?

Núria
