### ISSUE TITLE
Información entregable Práctica 1

### ISSUE THREAD

**Issue by llevaNEUS** [UB-GEI-SD/B#11]
Os he colgado un [documento](https://github.com/UB-GEI-SD/B/blob/master/Informaci%C3%B3n%20del%20entregable%20de%20la%20Pr%C3%A1ctica%201.pdf) .pdf con toda la información a tener en cuanta antes de entregar la práctica pero no hay nada relevante que no se haya comentado en clase.  Os recomiendo que lo leáis atentamente.

**Comment by hopefulhazel** [comment]
aleshores no es necessari la presencia de diagrames de seqüencia ni diagrames de seqüencia de sistema?

**Comment by llevaNEUS** [comment]
El que vulgueu, però com mínim un esquema de classes.

Núria
