### ISSUE TITLE
Dubte Pràctica de Django Admin (PracticaDjango3) - Homework 1

### ISSUE THREAD

**Issue by llevaNEUS** [UB-GEI-SD/B#15]
Ahir va sorgir el dubte sobre l'enunciat de la pràctica en el punt que posa: 
**1. Extend User django internal model with an attribute money and register an admin view for adding money to Users.**

En aquest apartat heu de fer que dins de /admin  quan ens loguegem com a usuari admin poguem modificar la nova clase "extended" User. Es fa de manera molt similar al que explica la mateixa pràctica al principi relacionat amb els Items i els permisos que donem a l'usuari Comercial per poder modificar aquests elements. Això us servirà per fer proves, ja que fem que quan creem l'usuari li assignem un nombre de diners per defecte (poseu 1000 o 2000 sino quasi no podreu comprar res) que no podreu modificar de cap altra manera que no sigui a través de /admin. Així que us serà útil per fer proves i que no hagueu d'anar creant usuaris cada vegada que aquests es queden sense diners. 

@jordipainan i @ejortizre7 queda més clar ara?  Ahir realment estava bastant griposa.

**Comment by jordipainan** [comment]
Perfecte! Ja està entès, moltes gràcies.

**Comment by jordipainan** [comment]
Ja està, sóc retarded i no havia caigut.
