### ISSUE TITLE
Jugador debe tener un ID para poder guardar el cómputo de dinero entre partida y partida

### ISSUE THREAD

**Issue by llevaNEUS** [UB-GEI-SD/B#3]
Si leéis el enunciado de la práctica pone: "En mode manual l’usuari ha de poder jugar tantes partides com vulgui. Haurà d’introduir el seu Identificador de jugador i a continuació podrà fer tantes partides com vulgui o pugui. En cas de no tenir suficients diners per entrar a una partida haurà de sortir".

Y en el protocolo no lo hemos tenido en cuenta. Simplemente se trata de añadir la trama UID<sp><int> (UID = "User ID") antes del compando PLY ("Play") para que afecte lo mínimo al protocolo hecho hasta el momento.

Esto servirá para que el servidor guarde el número de monedas asociado a un jugador y que cuando vuelva a conectarse empiece con lo que tenia de la partida anterior. El servidor no hace falta que tenga persistencia de memoria, así que si cerramos el servidor perdemos toda la memoria de clientes y monedas.

En caso de modo automático podéis hacer que el usuario tenga un ID por defecto.

Acabad de leer el enunciado de prácticas para ver si hay cualquier otra duda.

**Comment by Armengedon** [comment]
UID afegit a la wiki per a que en quedi constància.
