### ISSUE TITLE
Orden de los enteros de Stack

### ISSUE THREAD

**Issue by jordipainan** [UB-GEI-SD/B#4]
Stacks que recibe el cliente, el primer int es el stack del cliente o del server?
Propongo sea el primero del cliente. No se si se comentó en clase.

**Comment by llevaNEUS** [comment]
El primero es el del cliente.
Recuerdo que uno de los ejercicios a realizar es documentar todo el protocolo en la wiki y documento .nroff pero nadie está haciendo nada.
