### ISSUE TITLE
Enviament de les comandes

### ISSUE THREAD

**Issue by jordipainan** [UB-GEI-SD/B#7]
Hola hem fet la prova del protocol amb uns companys i tenim un dubte sobre com enviar les comandes des del servidor.

Opció 1: dos.write(BStr, 0, 13); On BStr és la comanda "STK"+" "+int+" "+int
Opció 2: dos.write(BStr, 0, 3); On Bstr és "STK" , dos.write(Bstr, 0, 1); On BStr és " " i així succesivament.

Potser és el mateix però amb la segona opció no ens llegeix bé el segon int, si per exemple enviem:
utils.write_int32(game.getStackClient()); On l'argument retorna un int = 100
El primer es reb correctament, però el segon essent enviant el mateix reb 8223832
Després la resta de comandes ja començen a rebres malament.

Alguna idea de què pot estar passant ? Quina opció, si es que està aquí contemplada, utilitzeu ?

**Comment by llevaNEUS** [comment]
Hola,
En principi hauria de ser el mateix però depen de com feu el read/write
space us pot donar problemes perquè un char per defecte en java és de 2
bytes, en canvi dintre d'un String és un byte, només els caràcters
especials no sigui utf-8 ocupen 2bytes.
Mireu que no hi hagi algun problema respecte als bytes que envieu (o creieu
enviar) i rebeu (o com els llegiu) a banda i banda. Per llegir/escriure
enters utlitzeu, si no ho feu, les comandes que ja hi havia a ComUtils:
read_int32/write_int32.
Jo personalment faig servir els writes separats però els dos mètodes
haurien de ser igual de vàlids. Feu la prova "cutre" d'escriure a fitxer la
comanda STK i demés, mireu que hi ha a fitxer (alguns bytes no seran
llegibles però sabreu quants bytes heu escrit pel tamany del fitxer) i
intenteu llegir-la. A veure si veieu alguna cosa rara i podeu detactar
l'error.

Núria

El dia 18 de març de 2018 a les 17:52, Jordi Piñana <
notifications@github.com> ha escrit:

**Comment by jordipainan** [comment]
Vale anirem testejant com dius.
Igualment el que esperem rebre en cas d'un espai és un char ' ' o un string " " ? Perquè llavors si canvia de 1 a 2 bytes, pot ser que es llegeixi malament si s'espera només rebre un byte o dos en cada cas. Hem de tenir en compte els dos casos o n'hi ha un d'especificat ? D'altra banda entenc que Card ve seguida d'un espai (1 o 2 bytes) i un char (1 byte) i no d'un string ("J" || "Q" || "K") com indica al protocol encara que ha efectes del joc la lògica és la mateixa. Seria a la capa del protocol.

**Comment by llevaNEUS** [comment]
Els caràcters a enviar són d'un byte, tant les cartes, com els torns, etc.
Treballeu a nivell de byte a l'hora del read i el write convertiu al que us
faci falta.

Núria

El dia 18 de març de 2018 a les 20:17, Jordi Piñana <
notifications@github.com> ha escrit:

**Comment by llevaNEUS** [comment]
Mireu com està fet write_string/read_string de ComUtils i adapteu-lo per
una string de longitud 1 per fer els casos d'un caràcter (1 byte).

Núria
