### ISSUE TITLE
ERR 03

### ISSUE THREAD

**Issue by jmcano94** [UB-GEI-SD/B#9]
Com no esta ben definit qui envia aquest error faig una proposta: 

Creiem que només servidor és l'encarregat d'enviar aquest error a un client quan aquest li envia un PLY i el client no té els tokens sufficients com per poder jugar una partida completa (2 tokens com a minim). Servidor tancará automaticament la conexió amb el client. 

En cas de que el servidor  no tingui més diners  proposem crear un nou ERR 05 que s'envia al client indicant-ho, tot seguit s'hauria de tallar la conexió amb el client.

**Comment by MrViciao** [comment]
El mínimo para jugar una partida es 1 token, siempre que luego limites las opciones de BET y CALL.

El servidor si se queda sin dinero, no puede parar la partida. Mas que lanzar un código de error, el servidor tendría que informar al cliente que no quiere seguir jugando, enviando PLAY/STOP como cliente. Pero creo que hacerlo mediante un código de error seria mas sencillo. ERR 05: SERVER LOST

Ademas, un caso que no hemos contemplado, es que pasa si el cliente se reconecta a una partida en la que el servidor no tiene dinero.

**Comment by MrViciao** [comment]
Yo haría que si en medio de una partida alguien se queda sin dinero por hacer un bet/call, se mande un Error 03, tanto el cliente como servidor. Si al final de una partida el servidor termina con 0 tokens, envía el ERROR 05 SERVER LOST y cierra conexión acto seguido.

**Comment by jmcano94** [comment]
Yo veo más logico que si ninguno de los 2 tiene suficiente dinero como para iniciar una partida (2 tokens) se envíe el error dependiendo de quien se haya quedado sin dinero (ERR 03 cliente, ERR 05 servidor), pero solo lo envía el servidor que es quien debe de controlar estos fallos, no el cliente.

**Comment by MrViciao** [comment]
Con 1 token se puede seguir jugando. Haz que la IA no seleccione Bet/Call si tiene 0 tokens.
Tanto el cliente como el servidor pueden mandar 03, ya que los dos tienen el valor del otro, con el comando STACK y pueden ver si el otro esta apostando cuando no puede.

**Comment by llevaNEUS** [comment]
**Demasiado tarde para hacer cambios/propuestas en el protocolo.**

Pero el único que tiene potestad cómo para decir que no hay dinero para jugar otra partida es el servidor, ya sea que él o el cliente no tiene dinero (el protocolo actual no distingue quien no tiene dinero). 
Siempre que se cierre la conexión con el cliente se le tiene que notificar el porque con un cadena error (aunque esta es posible que no llegue a su destinatario).
El control de los tokens mínimos para jugar y demás, eso a vuestro gusto.
